class StalcraftApiException(Exception): ...

# * Basic
class InvalidToken(StalcraftApiException): ...
class MissingCredentials(StalcraftApiException): ...

# * Api Requests
class ApiRequestError(StalcraftApiException): ...
class RequestUnauthorised(ApiRequestError): ...
class RequestInvalidParameter(ApiRequestError): ...
class RequestNotFound(ApiRequestError): ...
class RateLimitReached(ApiRequestError): ...

# * Item Id
class ItemIdError(StalcraftApiException): ...
class ListingJsonNotFound(ItemIdError): ...
class ItemIdNotFound(ItemIdError): ...
